planar_output: False # Output only x, y, and rotation about z

parent_frame_id: odom # TF frame id, override output_frame if set
child_frame_id: test_link #TF frame id

freq: 10.0 # In Hz, param name ported from robot_pose_ekf
update_rate: 10.0 # Overides 'freq' if set, in Hz
update_topic: odom # Which topic to trigger updates, if blank, uses timed update_rate, if '*', will trigger on all new topics

dt_override : 0.0 # Override the dt for update_rate or update_topic, ignored if 0

queue_size: 1

publish_tf: true

# Filter parameters

alpha: 0.001
kappa: 0.0
beta: 2.0

# Process noise covariance 2x2 for velocites, 5x5 for 2d position
process_noise: [1e1, 0, 0,
                0, 1e1, 0,
                0, 0, 1e1]
#process_noise: [1e6, 0, 0,
#                0, 1e6, 0,
#                0, 0, 1e6]

initial_covariance: [1, 0, 0,
                     0, 1, 0,
                     0, 0, 1]

topics: {
  odom: {
    topic: /odom,
    type: nav_msgs/Odometry,
    absolute_pose: False,
    use_velocities: True,
    delta_pose: False,
    timeout: 1.0,
    # override covariance       x,    y,    z,    roll, pitch, yaw
    override_pose_covariance: [ 0.1,  0.0,  0.0,  0.0,  0.0,   0.0,
                                0.0,  0.1,  0.0,  0.0,  0.0,   0.0,
                                0.0,  0.0,  0.1,  0.0,  0.0,   0.0,
                                0.0,  0.0,  0.0,  10.0, 0.0,   0.0,
                                0.0,  0.0,  0.0,  0.0,  10.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,   0.2 ],
    override_twist_covariance: [ 0.2,  0.0,  0.0,  0.0,  0.0,   0.0,
                                 0.0,  0.2,  0.0,  0.0,  0.0,   0.0,
                                 0.0,  0.0,  0.2,  0.0,  0.0,   0.0,
                                 0.0,  0.0,  0.0,  10.0, 0.0,   0.0,
                                 0.0,  0.0,  0.0,  0.0,  10.0,  0.0,
                                 0.0,  0.0,  0.0,  0.0,  0.0,   0.2 ],
  },

  imu: {
    topic: /imu_biased,
    type: sensor_msgs/Imu,
    absolute_orientation: False,
    use_velocities: True,
    use_accelerations: False,
    timeout: 1.0,
    # override covariances
    override_linear_acceleration_covariance: [ 0.14,  0.012,  -0.057,
                                               0.012, 0.085,  -0.078,
                                              -0.057, -0.078,  0.26],
    override_angular_velocity_covariance: [  9.0e-07,  1.77e-08,  2.24e-09,
                                             1.77e-08, 4.18e-07, -2.29e-10,
                                             2.24e-09, -2.29e-10, 3.00e-07],
  },

  compass: {
    topic: /compass_imu,
    type: sensor_msgs/Imu,
    absolute_orientation: True,
    use_velocities: False,
    use_accelerations: False,
    timeout: 1.0
  }
}
